name: todo_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  change_case: ^2.2.0
  dart_frog: ^1.2.3
  dart_frog_auth: ^1.2.1
  dart_jsonwebtoken: ^3.2.0
  dotenv: ^4.2.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mailer: ^6.5.0
  mongo_dart: ^0.10.0
  password_generator: ^1.0.0
  postgres: ^3.5.6
  string_validator: ^1.2.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.9.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^9.0.0
