name: todo_frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.2
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^16.2.0
  http: ^1.5.0
  intl: any
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path: "assets/icons/notes.png"
  image_path_android: "assets/icons/notes.png"
  image_path_ios: "assets/icons/notes.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/icons/todo.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/icons/todo.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  # adaptive_icon_monochrome: "assets/icons/todo.png" # only available for Android 13 devices and above
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # remove_alpha_ios: true
